version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/files:/store
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/store/spotimann.json
  database-song-information-service:
    image: 'mongo'
    container_name: 'database-song-information-service'
    volumes:
      - mongodata:/data/db 
    ports:
      - '27017:27017'
  node-song-information-service:
    image: node
    ports:
      - 8080:8080
    container_name: node-song-information-service
    volumes:
      - ./song-information-service:/src
    command: "node src/index.js"
    depends_on:
      - database-song-information-service
volumes:
  mongodata: