version: "3.8"
services:

  ### KEYCLOAK ###
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    container_name: "keycloak"
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/files:/store
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/store/spotimann.json

  ### SONG INFORMATION SERVICE ###
  database-song-information-service:
    image: "mongo"
    container_name: "database-song-information-service"
    volumes:
      - mongo-data-song-information:/data/db
    ports:
      - "27017:27017"
  mongo-seed-song-information:
    build:
      context: ./song-information-service/database
      dockerfile: Dockerfile
    depends_on:
      - database-song-information-service

  node-song-information-service:
    build:
      context: ./song-information-service
      dockerfile: Dockerfile
    ports:
      - 3001:8080
    container_name: node-song-information-service
    depends_on:
      - database-song-information-service

  ### RATING SERVICE ###
  database-rating-service:
    image: "mongo"
    container_name: "database-rating-service"
    volumes:
      - mongo-data-rating:/data/db
    ports:
      - "27018:27017"
  mongo-seed-rating:
    build:
      context: ./rating-service/database
      dockerfile: Dockerfile
    depends_on:
      - database-rating-service

  node-rating-service:
    build:
      context: ./rating-service
      dockerfile: Dockerfile
    ports:
      - 3002:8080
    container_name: node-rating-service
    depends_on:
      - database-rating-service
      - keycloak

  ### FRONTEND ###
  vue-frontend:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    container_name: vue-frontend

volumes:
  mongo-data-song-information:
  mongo-data-rating:
